const { Router } = require('express')
const { getProfile, getCheckout, updateImage, getAddress, updateProfileVii } = require('../controllers/profile')
const { editAddress, changeStatus, deleteAddress, getPriAddress } = require('../controllers/users')
const { buy, getHistoryTransaction } = require('../controllers/transaction')
const uploadHelper = require('../helpers/upload')
const router = Router()

router.get('/', getProfile)
router.patch('/seller')
router.patch('/customer', updateProfileVii)
router.patch('/customer/img', uploadHelper, updateImage)
router.get('/checkout', getCheckout)
router.get('/address', getAddress)
router.get('/address/primary', getPriAddress)
router.patch('/address/edit/:id', editAddress)
router.patch('/address/change/:id', changeStatus)
router.delete('/address/delete/:id', deleteAddress)
router.post('/buy', buy)
router.get('/history', getHistoryTransaction)

module.exports = router
